name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  mac:
    runs-on: macOS-latest
    steps:
    - name: Checkout
    uses: actions/checkout@v1
    - name: Build
      run: ./build.sh
